title: Welcome to Open Source and GitHub Workshop.
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    mspevent       
author-image:   1.png
author-job:     Kamla Nehru Institute of Technology, Sultanpur 
author-email:   dev.18715@knit.ac.in # Add your email for contant form.
author-twitter: devtweets  # Add your twitter account
about-author:   Welcome to Kamla Nehru Institute of Technology, Sultanpur. This Page is designed for the Details of upcoming Events 
hosted by Microsoft Student Partner. Slide through the Pages which will give you brief about the Event Details.
# Social settings
social-twitter:   devtweeets
social-facebook:  beliked3v
social-github:    mspevent
social-pinterest: 
social-instagram: beliked3v
social-youtube:   
social-vk:   
social-linkedin: idevprakaash
social-mail: dev.18715@knit.ac.in

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: UA-93525237-2 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: Admin-Dev # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-compose
  - jemoji

paginate: 5
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

gems: 
      - jekyll-sitemap

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
