title: Welcome Coders!
description: codewithdev is a fully-fledged Technical Blog which is drawing your attention all the time.
baseurl: "https://codewithdev.github.io" # the subpath of your site, e.g. /blog
url: "https://codewithdev.me" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Dev Prakash Sharma        
author-image:   1.jpg
author-job:     Web Developer | Tech Enthusiast | Blogger | AI & ML | Ethical Hacker
author-email:   dev.18715@knit.ac.in # Add your email for contant form.
author-twitter: devtweets  # Add your twitter account
about-author:   An Open Source advocate with interest in Technology. Web Developer, Tech Enthusiast.
       Former Machine Learning Intern at IIT Roorkee. Currently working in Projects using Machine Learning and Deep Learning.

# Social settings
social-twitter:   devtweets
social-facebook:  beliked3v
social-github:    codewithdev
social-pinterest: 
social-instagram: beliked3v
social-youtube:  Dev Prakash Sharma
social-vk:   
social-linkedin: idevprakaash
social-mail: dev.18715@knit.ac.in

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: Admin-Dev # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-compose
  - jemoji

paginate: 5
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
